#!/bin/sh
# aws-greengrass-sdk-lite - Lightweight AWS IoT Greengrass SDK
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -e

cd rust
bindgen wrapper.h \
  -o src/c.rs \
  --default-enum-style rust \
  --generate-inline-functions \
  --enable-function-attribute-detection \
  --disable-nested-struct-naming \
  --with-derive-default \
  --disable-header-comment \
  --no-doc-comments \
  --use-core \
  --generate-cstr \
  --sort-semantically \
  --allowlist-function 'gg_.*' \
  --allowlist-function 'ggipc_.*' \
  --allowlist-type 'Gg.*' \
  --allowlist-type 'GgIpc.*' \
  --allowlist-var 'GG_.*' \
  --raw-line '// aws-greengrass-sdk-lite - Lightweight AWS IoT Greengrass SDK' \
  --raw-line '// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.' \
  --raw-line '// SPDX-License-Identifier: Apache-2.0' \
  --raw-line "" \
  --raw-line '//! Generated by bindgen' \
  --raw-line "" \
  --raw-line '#![allow(non_upper_case_globals)]' \
  --raw-line '#![allow(non_camel_case_types)]' \
  --raw-line '#![allow(non_snake_case)]' \
  --raw-line '#![allow(dead_code)]' \
  --raw-line '#![allow(clippy::pedantic)]' \
  --raw-line "" \
  --raw-line 'pub const GG_OBJ_NULL: GgObject = GgObject { _private: [0; 11] };' \
  -- -I../include
